/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zoiowo (https://sketchfab.com/Zoiowo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/harley-dream-caster-d257bee56ccf4686a215b4889dce6681
Title: Harley - Dream Caster
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Harley(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/harley_-_dream_caster.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[1].name]?.play();
    }
  }, [actions, animations]);
  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-2.8);
  }, [ySpring]);
  useFrame(() => {
    group.current.position.y = ySpring.get();
  });
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={props.rotation || [-Math.PI / 1.8, 0, -0.5]}
      scale={props.scale || 2.5}
      position={props.position || [1.8, -2.8, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model">
          <group
            name="hero_moshushi_skin06_high_addfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={1}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.zhengtai_skin06_high2}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.zhengtai_skin06_high}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.zhengtai_skin06_high_hair}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.zhengtai_skin06_high3}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="Object_10" position={[0, 1.392, 0.146]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/harley_-_dream_caster.glb");
